### ISSUE TITLE
Add confirmation toast on clicking "save" from user management modal

### ISSUE THREAD

**Issue by ghost** [RoboJackets/onken-web#2]
- Use [Ant Design Message](https://ant.design/components/message/)
- Change Modal to mock loading with a setTimeout; Ant Design has an option for showing a loading spinner
- Fire a message.success at the end of the timeout

**Comment by AjinkyaKaley** [comment]
Hi, I would like to work on this issue.

**Comment by ghost** [comment]
Hey, thanks for offering to help @AjinkyaKaley! Just pull the latest master and head over to pages -> admin -> user-management. The demo confirmation message will go in the component defined in index.js. [This](https://ant.design/components/modal/) is a good resource to see how Ant Design modals work. I'll review your pull request. Happy hacking!

**Comment by ghost** [comment]
^ Sorry, clicked the wrong issue on my last pull request. This issue is still open
