### ISSUE TITLE
Set up Sentry for serverside and clientside error handling

### ISSUE THREAD

**Issue by ghost** [RoboJackets/onken-web#7]
- Should catch client exceptions using Raven in _app.js
- Should catch server exceptions within Express.js

**Comment by kberzinch** [comment]
There's a RoboJackets sentry account, log in with GitHub and it should let you in.

**Comment by ghost** [comment]
I logged in with my GitHub and used RoboJackets as the org name. Didn't seem to link up.

**Comment by kberzinch** [comment]
Try sentry.io/robojackets

**Comment by ghost** [comment]
Alright, client side error capturing was easy enough. Looks like ExpressJS is only going to be used for handling route masking, so no need to configure Sentry there. Server side error capturing continues to be a challenge. There's a few NextJS issues open about it with some community suggestions that I'll look into.

The PR for this issue will also include setup for environment variables loaded in with Babel. This is needed to store the `SENTRY_DSN`

**Comment by kberzinch** [comment]
I still don't see the frontend project in sentry.

I understand Express isn't going to be used for much, but please add Sentry integration for it just in case there's some weird issue.
